### ISSUE TITLE
WeeNES is an illegal mess

### ISSUE THREAD

**Issue by waddlesplash** [kallisti5/WeeNES#5]
I've identified some problems, working with WeeNES:

 * It's a mess. Abstract classes, bad design... it isn't too great.
 * It's illegal. The M6502 library it uses is [under a license that is not compatible with the GPL](http://fms.komkon.org/EMUL8/).

So we have 2 options:
 * Fix all the legal issues by moving to a different 6502 core (tough, the code is pretty bad)
 * Wipe WeeNES off the face of the earth, and start with some other NES emulator and Haiku-ize it ([LameNES looks nice](http://lamenes.org/index.html) -- we can add a "B" to the name and call it "BlameNES"... xD)

**Comment by kallisti5** [comment]
I'm fine with this going away. It stated as a "port beos nes emulator to haiku" project. I likely never dug much beyond the interface code.  HuExpress is my baby now (and not illegal :-))

There is a recipe as well I think out there. I'm going to erase this repo in a few days to leave a little time for anyone to fork it.

**Comment by kallisti5** [comment]
My diff for the latest BeNES -> WeeNES is here: https://gist.github.com/kallisti5/86188b9fc6309ba085e7
